#!/usr/bin/env bash
# Bootstrap Scanimal into a Cloudflare account.
# Requires: wrangler CLI authenticated (run `wrangler login` first), openssl.
#
# Usage:
#   ./scripts/bootstrap.sh                  # interactive
#   PROJECT_NAME=myqr ./scripts/bootstrap.sh   # non-interactive

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
PROJECT_NAME="${PROJECT_NAME:-scanimal}"
DB_NAME="${PROJECT_NAME}-db"
KV_TITLE="${PROJECT_NAME}-links"
R2_BUCKET="${PROJECT_NAME}-assets"
OUTPUT_WRANGLER="wrangler.jsonc"
OUTPUT_ENV=".env.local"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║   Scanimal — Cloudflare Bootstrap         ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Check prerequisites ───────────────────────────────────────────────────────
if ! command -v wrangler &>/dev/null; then
  echo "❌ wrangler not found. Run: pnpm install && pnpm wrangler login"
  exit 1
fi

if ! command -v openssl &>/dev/null; then
  echo "❌ openssl not found. Install it via your package manager."
  exit 1
fi

echo "✓ wrangler found: $(wrangler --version 2>/dev/null | head -1)"
echo ""

# ── Cloudflare account ID ─────────────────────────────────────────────────────
ACCOUNT_ID=$(wrangler whoami 2>/dev/null | grep -oE '[0-9a-f]{32}' | head -1 || echo "")
if [ -z "$ACCOUNT_ID" ]; then
  echo "❌ Could not detect Cloudflare account ID. Run: wrangler login"
  exit 1
fi
echo "✓ Cloudflare account: $ACCOUNT_ID"

# ── D1 database ───────────────────────────────────────────────────────────────
echo ""
echo "▸ Creating D1 database \"$DB_NAME\"..."
D1_OUTPUT=$(wrangler d1 create "$DB_NAME" 2>&1 || true)

if echo "$D1_OUTPUT" | grep -q "database_id"; then
  D1_ID=$(echo "$D1_OUTPUT" | grep -oE '"database_id":\s*"[^"]+"' | grep -oE '[0-9a-f-]{36}')
  echo "  ✓ Created D1: $D1_ID"
elif echo "$D1_OUTPUT" | grep -qi "already exists"; then
  D1_ID=$(wrangler d1 list 2>/dev/null | grep "$DB_NAME" | grep -oE '[0-9a-f-]{36}' | head -1 || echo "")
  if [ -z "$D1_ID" ]; then
    echo "  ❌ D1 database exists but could not read its ID. Check Cloudflare dashboard."
    exit 1
  fi
  echo "  ↩ D1 already exists: $D1_ID"
else
  echo "  ❌ Unexpected D1 output:"
  echo "$D1_OUTPUT"
  exit 1
fi

# ── KV namespace (slug → destination hot cache for the redirect path) ────────
echo ""
echo "▸ Creating KV namespace \"$KV_TITLE\"..."
KV_OUTPUT=$(wrangler kv namespace create "$KV_TITLE" 2>&1 || true)

if echo "$KV_OUTPUT" | grep -qE '"?id"?[:=]?\s*"?[0-9a-f]{32}'; then
  KV_ID=$(echo "$KV_OUTPUT" | grep -oE '[0-9a-f]{32}' | head -1)
  echo "  ✓ Created KV: $KV_ID"
elif echo "$KV_OUTPUT" | grep -qi "already exists"; then
  KV_ID=$(wrangler kv namespace list 2>/dev/null | grep -B2 -A2 "$KV_TITLE" | grep -oE '[0-9a-f]{32}' | head -1 || echo "")
  if [ -z "$KV_ID" ]; then
    echo "  ❌ KV namespace exists but could not read its ID. Check Cloudflare dashboard."
    exit 1
  fi
  echo "  ↩ KV already exists: $KV_ID"
else
  echo "  ❌ Unexpected KV output:"
  echo "$KV_OUTPUT"
  exit 1
fi

# ── R2 bucket (logo uploads) ──────────────────────────────────────────────────
echo ""
echo "▸ Creating R2 bucket \"$R2_BUCKET\"..."
R2_OUTPUT=$(wrangler r2 bucket create "$R2_BUCKET" 2>&1 || true)
if echo "$R2_OUTPUT" | grep -qiE "created|already exists"; then
  echo "  ✓ R2 bucket ready: $R2_BUCKET"
else
  echo "  ⚠ Could not create R2 bucket (logo uploads will be unavailable):"
  echo "$R2_OUTPUT"
fi

# ── Generate wrangler.jsonc from template ─────────────────────────────────────
echo ""
echo "▸ Writing $OUTPUT_WRANGLER..."
sed \
  -e "s/{{D1_DATABASE_ID}}/$D1_ID/g" \
  -e "s/{{KV_NAMESPACE_ID}}/$KV_ID/g" \
  -e "s/{{R2_BUCKET_NAME}}/$R2_BUCKET/g" \
  -e "s/{{ACCOUNT_ID}}/$ACCOUNT_ID/g" \
  wrangler.template.jsonc > "$OUTPUT_WRANGLER"
echo "  ✓ Written: $OUTPUT_WRANGLER"

# Note: the Analytics Engine dataset (qr_scans) needs no provisioning — it is
# created automatically on first write via the SCANS binding.

# ── Generate BETTER_AUTH_SECRET ───────────────────────────────────────────────
echo ""
echo "▸ Generating BETTER_AUTH_SECRET..."
AUTH_SECRET=$(openssl rand -base64 32)

# Write to .env.local (never committed)
if [ -f "$OUTPUT_ENV" ]; then
  if grep -q "BETTER_AUTH_SECRET" "$OUTPUT_ENV"; then
    echo "  ↩ BETTER_AUTH_SECRET already set in $OUTPUT_ENV — skipping."
  else
    echo "BETTER_AUTH_SECRET=\"$AUTH_SECRET\"" >> "$OUTPUT_ENV"
    echo "  ✓ Appended BETTER_AUTH_SECRET to $OUTPUT_ENV"
  fi
else
  cat > "$OUTPUT_ENV" <<EOF
# Generated by scripts/bootstrap.sh — do not commit this file.
CLOUDFLARE_ACCOUNT_ID="$ACCOUNT_ID"
CLOUDFLARE_DATABASE_ID="$D1_ID"

# For local dev, wrangler reads from .dev.vars — put secrets there too.
# For production, run: wrangler secret put BETTER_AUTH_SECRET
BETTER_AUTH_SECRET="$AUTH_SECRET"

# Set ORIGIN to your deployed Workers URL or custom domain.
ORIGIN="http://localhost:5173"

# ── Email (magic links + invites). Optional — single-user deployments can skip.
# EMAIL_FROM="login@yourdomain.com"
# EMAIL_PROVIDER="cloudflare"        # cloudflare (Workers Paid) | resend | none
# RESEND_API_KEY=""                  # only when EMAIL_PROVIDER=resend

# ── Analytics dashboard reads (AE SQL API). Optional.
# CF_ANALYTICS_TOKEN=""              # API token with Account Analytics read

# ── Social auth. Optional, off by default.
# GOOGLE_CLIENT_ID="" GOOGLE_CLIENT_SECRET=""
# GITHUB_CLIENT_ID="" GITHUB_CLIENT_SECRET=""
EOF
  echo "  ✓ Created $OUTPUT_ENV"
fi

# ── Run D1 migrations ─────────────────────────────────────────────────────────
echo ""
echo "▸ Running database migrations (remote, via wrangler)..."
if wrangler d1 migrations apply "$DB_NAME" --remote; then
  echo "  ✓ Migrations applied."
else
  echo "  ⚠ Migration step failed — run 'pnpm wrangler d1 migrations apply $DB_NAME --remote' manually."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════"
echo "  Bootstrap complete!"
echo ""
echo "  Next steps:"
echo "  1. Copy BETTER_AUTH_SECRET from .env.local to .dev.vars for wrangler dev:"
echo "       echo 'BETTER_AUTH_SECRET=\"...\"\nORIGIN=\"http://localhost:5173\"' > .dev.vars"
echo "  2. Start the dev server:"
echo "       pnpm dev"
echo "  3. For production, set secrets in Cloudflare:"
echo "       wrangler secret put BETTER_AUTH_SECRET"
echo "══════════════════════════════════════════════"
echo ""
