#!/usr/bin/env bash
# Bootstrap Scanimal into a Cloudflare account.
# Requires: wrangler CLI authenticated (run `wrangler login` first), openssl.
#
# Usage:
#   ./scripts/bootstrap.sh                  # interactive
#   PROJECT_NAME=myqr ./scripts/bootstrap.sh   # non-interactive

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
PROJECT_NAME="${PROJECT_NAME:-scanimal}"
DB_NAME="${PROJECT_NAME}-db"
OUTPUT_WRANGLER="wrangler.jsonc"
OUTPUT_ENV=".env.local"

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║   Scanimal — Cloudflare Bootstrap         ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Check prerequisites ───────────────────────────────────────────────────────
if ! command -v wrangler &>/dev/null; then
  echo "❌ wrangler not found. Run: pnpm install && pnpm wrangler login"
  exit 1
fi

if ! command -v openssl &>/dev/null; then
  echo "❌ openssl not found. Install it via your package manager."
  exit 1
fi

echo "✓ wrangler found: $(wrangler --version 2>/dev/null | head -1)"
echo ""

# ── Cloudflare account ID ─────────────────────────────────────────────────────
ACCOUNT_ID=$(wrangler whoami 2>/dev/null | grep -oE '[0-9a-f]{32}' | head -1 || echo "")
if [ -z "$ACCOUNT_ID" ]; then
  echo "❌ Could not detect Cloudflare account ID. Run: wrangler login"
  exit 1
fi
echo "✓ Cloudflare account: $ACCOUNT_ID"

# ── D1 database ───────────────────────────────────────────────────────────────
echo ""
echo "▸ Creating D1 database \"$DB_NAME\"..."
D1_OUTPUT=$(wrangler d1 create "$DB_NAME" 2>&1 || true)

if echo "$D1_OUTPUT" | grep -q "database_id"; then
  D1_ID=$(echo "$D1_OUTPUT" | grep -oE '"database_id":\s*"[^"]+"' | grep -oE '[0-9a-f-]{36}')
  echo "  ✓ Created D1: $D1_ID"
elif echo "$D1_OUTPUT" | grep -qi "already exists"; then
  D1_ID=$(wrangler d1 list 2>/dev/null | grep "$DB_NAME" | grep -oE '[0-9a-f-]{36}' | head -1 || echo "")
  if [ -z "$D1_ID" ]; then
    echo "  ❌ D1 database exists but could not read its ID. Check Cloudflare dashboard."
    exit 1
  fi
  echo "  ↩ D1 already exists: $D1_ID"
else
  echo "  ❌ Unexpected D1 output:"
  echo "$D1_OUTPUT"
  exit 1
fi

# ── Generate wrangler.jsonc from template ─────────────────────────────────────
echo ""
echo "▸ Writing $OUTPUT_WRANGLER..."
sed \
  -e "s/{{D1_DATABASE_ID}}/$D1_ID/g" \
  -e "s/{{ACCOUNT_ID}}/$ACCOUNT_ID/g" \
  wrangler.template.jsonc > "$OUTPUT_WRANGLER"
echo "  ✓ Written: $OUTPUT_WRANGLER"

# ── Generate BETTER_AUTH_SECRET ───────────────────────────────────────────────
echo ""
echo "▸ Generating BETTER_AUTH_SECRET..."
AUTH_SECRET=$(openssl rand -base64 32)

# Write to .env.local (never committed)
if [ -f "$OUTPUT_ENV" ]; then
  if grep -q "BETTER_AUTH_SECRET" "$OUTPUT_ENV"; then
    echo "  ↩ BETTER_AUTH_SECRET already set in $OUTPUT_ENV — skipping."
  else
    echo "BETTER_AUTH_SECRET=\"$AUTH_SECRET\"" >> "$OUTPUT_ENV"
    echo "  ✓ Appended BETTER_AUTH_SECRET to $OUTPUT_ENV"
  fi
else
  cat > "$OUTPUT_ENV" <<EOF
# Generated by scripts/bootstrap.sh — do not commit this file.
CLOUDFLARE_ACCOUNT_ID="$ACCOUNT_ID"
CLOUDFLARE_DATABASE_ID="$D1_ID"

# For local dev, wrangler reads from .dev.vars — put secrets there too.
# For production, run: wrangler secret put BETTER_AUTH_SECRET
BETTER_AUTH_SECRET="$AUTH_SECRET"

# Set ORIGIN to your deployed Workers URL or custom domain.
ORIGIN="http://localhost:5173"
EOF
  echo "  ✓ Created $OUTPUT_ENV"
fi

# ── Run D1 migrations ─────────────────────────────────────────────────────────
echo ""
echo "▸ Running database migrations (remote)..."
pnpm db:migrate 2>/dev/null && echo "  ✓ Migrations applied." || echo "  ⚠ Migration step skipped — run 'pnpm db:migrate' manually after setting CLOUDFLARE_D1_TOKEN."

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════"
echo "  Bootstrap complete!"
echo ""
echo "  Next steps:"
echo "  1. Copy BETTER_AUTH_SECRET from .env.local to .dev.vars for wrangler dev:"
echo "       echo 'BETTER_AUTH_SECRET=\"...\"\nORIGIN=\"http://localhost:5173\"' > .dev.vars"
echo "  2. Start the dev server:"
echo "       pnpm dev"
echo "  3. For production, set secrets in Cloudflare:"
echo "       wrangler secret put BETTER_AUTH_SECRET"
echo "══════════════════════════════════════════════"
echo ""
